### ISSUE TITLE
Foliage in air

### ISSUE THREAD

**Issue by CREEATION** [PersonTheCat/CaveGenerator#20]
MC: `1.12.2`
Forge: `14.23.5.2824`
Seed: `5768783229991403274`
World Type: `Default`
Coords: `/tp Notch -1105 26 446`

Is it possible to prevent this somehow on my end? My wild guess is that the ravine generates later than the foliage or something, which removes blocks but not the foliage itself.

//e: I'm just now seeing that I had a bunch of other mods installed, so the seed might not work and this issue might not be an issue. Can test tomorrow again.

![2019-04-11_06 56 40](https://user-images.githubusercontent.com/3277769/55932878-b023dc00-5c2b-11e9-9163-5fe41f6853b2.png)

**Comment by CREEATION** [comment]
Can confirm this does still happen without other mods:
![2019-04-12_04 25 34](https://user-images.githubusercontent.com/3277769/56008380-62b37780-5cdc-11e9-80df-9c3bed12f7e7.png)

Seed as above.
Coords: `/tp Notch -1063 30 327`
Only using the `underground_forest.cave` (unmodified) preset.

//e: Should note that I'm using your new `0.15` version right now.

**Comment by PersonTheCat** [comment]
This occurs when using multiple presets simultaneously. The problem is that the second preset in the queue doesn't know that it should replace these blocks. You can fix it by adding them to the replaceable block list where necessary. Feel free to suggest more ergonomic ways of handling this issue.

Edit: I forgot to mention that a better option is to rename the presets to adjust the order in which they get loaded. The preset which spawns this foliage will not do so if there's already air in place.
