### ISSUE TITLE
Presets stop generating with spectator in server

### ISSUE THREAD

**Issue by ghost** [PersonTheCat/CaveGenerator#23]
I am using cave generator 0.14, first situation I used the underground forest preset with lots of mods, then I tried just the large caves preset with only natural nether portals mod installed.

Both times, when I delete the world file and started my server, when I went spectator and went into the ground, the caves generated fine as usual, but when I moved (still in spectator mode) to any direction, eventually the caves stopped generating.

The surface loaded, and the pockets/holes(spheres) still spawned underground, or even dungeons spawned, but no caves, and they did not regenerate either.

I have done this in single player and it worked just fine, but when I run on my server then the issues begin.

**Comment by PersonTheCat** [comment]
Hey, there. My guess would be that this bug is actually related to version differences. There were some changes between Forge versions that led to inconsistencies in when generators were getting loaded and, more importantly, when they were getting *unloaded*. I wound up fixing this bug several weeks ago, but never released anything because I still feel like it needs a better fix. @duely has actually written a [similar fix](https://github.com/duely/CaveGenerator) independently which is superior in that it handles loading additional generators on a per-dimension basis. I have yet to test it due to some real life type issues that I'm still trying to work through first. In the meantime, you can download and try my current fix below and let me know if it fixes things for you. Hope this helps!

[CaveGenerator-0.15.zip](https://github.com/PersonTheCat/CaveGenerator/files/3269022/CaveGenerator-0.15.zip)

**Comment by noobanidus** [comment]
Yes, there is a binary of my fix around somewhere, but given that I don't know the mod anywhere near as well as Person, I'm not 100% confident that it doesn't actually cause other problems, and I don't want to promote it.

**Comment by PersonTheCat** [comment]
Fixed in 0.15.
