### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by crazybytes** [PersonTheCat/CaveGenerator#24]
I get no caves at all. Tried anything.
Do i just have to enable a few things, create a new level (with dirt/blocks set), then use /cave test to dive, but nothing shows up....Followed all internet traffic.....
Everybody seems how to use it.
I have latest minecraft launcher, forge 1.12.2.

**Comment by crazybytes** [comment]
Like do i have to adapt something in the options.txt file in the .minecraft dir, there is 
resourcePacks:["vanilla","programer_art"]
Inside it. Do i have to use the vanilla.cave, or .json file?
Do i have to put them somewhere?
Do i have to adapt some files?
Please help me out.

**Comment by crazybytes** [comment]
Do i have to copy the vanilla.json contents into the preset settings box within customize presets settings?
Custom generated world? Flat, with more dirt/stone?

**Comment by PersonTheCat** [comment]
If you're still seeing vanilla.json instead of vanilla.cave, you're most likely using an obsolete version of the mod. You might do well to update. If all you're trying to do is use the included presets, you shouldn't have to do anything by default to see vanilla-style caves generated by the vanilla preset. To change which preset you're using, you either need to put it in the `.../config/cavegenerator/presets` directory, open it up, and set `enabled` to `true` or just run the command `/cave list` and click to enable or disable whichever ones you want to use. Nothing needs to be changed by default to see any effects unless you want to create your own presets. Hope this helps!

**Comment by crazybytes** [comment]
ok!

Op di 20 aug. 2019 om 03:29 schreef PersonTheCat <notifications@github.com>:
