### ISSUE TITLE
Floating plants in generated caves

### ISSUE THREAD

**Issue by katubug** [PersonTheCat/CaveGenerator#27]
Okay so first off *holy crap, dude*, how have I been sleeping on this mod? I am genuinely so impressed, I love it.

I've just been flying around in Spectator, testing out the given presets, but I did notice some weirdness with floating grass and mushrooms here:
![2019-12-16_17 23 05](https://user-images.githubusercontent.com/20935286/70951508-3ac5a200-2029-11ea-8c04-f455d9ef74a2.png)

Most of it decayed and dropped as items once I changed back to creative and hovered nearby, but not all of them. Ultimately it's likely not a *huge* deal, because Minecraft terrain generation is A Thing anyway, and a couple of levitating herbs aren't a dealbreaker for me. But I thought I'd report.

I also have just a quick question - does this mod activate only in the overworld? I didn't see anything that would allow white or black listing by dimension, but I'd love to be able to use this in other dimensions, ideally on a per-preset basis.

Thanks for your time, and for the fantastic mod!

**Comment by katubug** [comment]
There's also a smidge of weirdness with the water generation.

![2019-12-16_17 53 22](https://user-images.githubusercontent.com/20935286/70952789-f89e5f80-202c-11ea-9f22-ba19a2278779.png)

Also I realized I forgot to give information on my environment:
- Forge 2847
- Cave Generator 0.16
- Quark, AutoRegLib, JEI, Misty World, Patchouli, The One Probe.

The presets I have enabled are:
- flooded_vanilla
- large_stalactites
- underground_forest
- vanilla

**Comment by PersonTheCat** [comment]
Hey, it looks like I never responded to this back in the day. I'm really sorry about that. I had gotten this issue several times in the past and always came to the same conclusion: this isn't exactly a bug with *Cave Generator*, it's a bug with how some *presets are implemented*. Ultimately, it depends on the order in which they're loaded and can be fixed by renaming them to change their load order.

For anyone reading this today, the thing to do if you encounter one of these issues is bring it up on [Discord](https://discord.gg/UNsXfvA). I'm always there and can help you get setup.

Let me know if you need anything else!
