### ISSUE TITLE
[BUG] [CRASH] Compatibility with SpongeForge

### ISSUE THREAD

**Issue by InlustrisXIII** [PersonTheCat/CaveGenerator#28]
Hi there, I am working on a fork of a modpack that your mod is involved in, Rebirth of the Night. I am attempting to make the pack compatible with SpongeForge, a server API that provides an extra layer of features on top of Forge. I have fixed several issues, and was getting ready to commit my changes, when I reached this crash error: 

https://pastebin.com/KnRYaaQn

And this one has left me stumped. Even installing spongeforge after generating a large area from spawn, it gives me this crash.
@PersonTheCat, if you can give me any insight into this, I would greatly appreciate it.

Edit: If you need any more information, let me know.

**Comment by PersonTheCat** [comment]
This looks like the mod just tried to read a block at y=256, which out of bounds (y>255). But, I can't really tell because you're using an outdated version of the mod. The latest is 0.18 and then there are development builds out there for 0.19 as well. 

I believe Foreck is working on updating this modpack to include version 0.18, but you should be able to just upgrade because they're 99.9% backward-compatible. Is there any way you could upgrade to at least 0.18 to confirm if that fixes the issue or get a better crash report?

**Comment by InlustrisXIII** [comment]
Yes, I will give it a shot. Thank you.

**Comment by PersonTheCat** [comment]
Closing this issue. Feel free to reopen it if the problem comes back up in 1.0+.
