### ISSUE TITLE
Crash when generating new world in v0.4

### ISSUE THREAD

**Issue by Cuplex17** [PersonTheCat/CaveGenerator#6]
Hello,
When I generate a new world, it gives me the crash attached. It seems to be a compatibility issue with biomes o plenty. 

[crash-2018-08-02_17.57.28-server.txt](https://github.com/PersonTheCat/CaveGenerator/files/2252626/crash-2018-08-02_17.57.28-server.txt)

**Comment by pirone2** [comment]
Seconding this. I get the same crash.
https://paste.dimdev.org/ixisihikow.mccrash

**Comment by PersonTheCat** [comment]
I'm so glad you sent me this. This is definitely not an incompatibility with BOP, but it is totally my fault. I'm actually shocked that this isn't causing crashes for me. I've tested both in my workstation and in a normal game without experiencing a crash, but at the same time, I _should have._ 

The only issue is that, because I still haven't experienced this, I don't have any way to verify that my changes have fixed the problem, so I'll need to send you a test build in a few minutes. If either of you can verify that it's working, that would be extremely helpful.

**Comment by PersonTheCat** [comment]
Here's the newest build. The same array is no longer accessed unless stone layers are registered, as it should have been before. Please let me know if this fixes the problem for you or if there are any new issues. Thanks again! 

[cavegenerator-0.4.1.zip](https://github.com/PersonTheCat/CaveGenerator/files/2254554/cavegenerator-0.4.1.zip)

**Comment by Cuplex17** [comment]
This fixed the problem. Thank you! However, is there a way to change the ravine generation more in depth? (i.e. Change what the floor block is and in what frequency, change the walls etc)

**Comment by PersonTheCat** [comment]
Actually, yes. All of these things are possible. Take a look at the ravines and tunnel presets. The only thing that might not be exactly what you're expecting is that floor blocks (and all other block fillers) are universal, so they would get placed anywhere where there's air above stone. But there are multiple ways to change the walls and you can also change the frequency. Let me know if you have trouble with any part in particular.
