### ISSUE TITLE
[SUGGESTION]Make  "blockFillers" function support caves generate by other mod

### ISSUE THREAD

**Issue by zzzqh** [PersonTheCat/CaveGenerator#8]
Such as 
Worley's Caves 
https://minecraft.curseforge.com/projects/worleys-caves
Subterranean Waters 
https://minecraft.curseforge.com/projects/subterranean-waters

**Comment by PersonTheCat** [comment]
This would be really cool. Unfortunately, there isn't really a way to do this safely. I have to reflectively send calls to these other mods in a way that requires me to program support for them specifically, or at least the user would need to understand each mod's code before trying. But even still, it would be very likely to cause crashes and would not perform very well. Or even more likely, it just wouldn't work. Subterranean Waters does have some pretty good config options, however, so definitely check those out if you haven't already. Those two mods can run together, but I don't think the same is possible for Worley's Caves because each mod uses the same Forge event and only one can fire at a time. In the meantime, I'm still working on new cave shapes, but I'm going to deliberately avoid copying Worley's Caves, for now. 

Thanks for the suggestions! Let me know your thoughts or if you have any other ideas.

**Comment by zzzqh** [comment]
Thank you for the detailed answer

1,Yep, I konw Subterranean Waters can run together. Just be curious about if it is possible to make an individual event progress after all cave generating  (include other mods), so that it can check and replace or add blocks without sending calls to other mods.

2,The reason why I try to use Worley's Caves is that I think caves(include ravine,mineshaft and dungen) is not very dense enough. Is there any ways to adjust it ?

3,By the way, I don't really understand the meaning of "noise" which appears in both your and Subterranean Waters' config. Could you give some instructions? Is it relate to some flat cave border such like this? And how could I  prevent it?
https://imgur.com/a/WclrS24
https://imgur.com/a/vRWBQTH

4,Moreover,If you still work on the shape of caves, I think you should take a look about TheMasterCaver's World Underground ,it give me a shock in 1.7.10 version, but sadly it doesn't update now.
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292668-1-7-1-13-themastercavers-mods-and-tweaks

**Comment by PersonTheCat** [comment]
Wow, thanks. I'm gonna start with 2. 

2. You totally can adjust this. You can increase the overall number of tunnels using "frequency" and even make them more likely to spawn in groups by lowering "spawnInSystemInverseChance" from 4 to 3, or 2, etc. Ravines work differently. They actually just have a chance to start spawning once in any chunk, because they're so large. The key for that is "inverseChance." By default, it's 50. That means that 1 / (50 + 1) chunks will start a new ravine. Setting it to 2, for example, would mean that basically everything becomes a ravine. 

3. The only time I've seen these kinds of walls in CG is when caverns are only enabled in specific biomes. I have a way to fade them out, but it's honestly just not all that good yet. :( If not, let me see your preset. I'll try using it myself and help you figure it out. 

4. Thanks for the suggestion. Another user was telling me about it and it looks like a really impressive mod. The developer is definitely still around and active in the community. Much of the functionality from that mod should ultimately be possible with CG. I'm looking to it for inspiration, but of course, I always love to hear new ideas. So, let me know!

**Comment by zzzqh** [comment]
Thanks,I will try and give report as well as other suggestion

**Comment by TheDeviantCrafter** [comment]
Worley's Caves uses a completely different noise map for cave generation. Making the two mods compatible would be a mess.

Personally, I was hoping to use both mods together, but not in the way mentioned in the issue. I want to use Worley's Caves for most of the cave generation, then use this mod for rare but massive or special caves.

Can the two mods both generate their caves at the same time, even if they don't really interact?

**Comment by PersonTheCat** [comment]
So, I think the problem is that Forge only allows one instance of each type of MapGenBase to be registered at a time. So, for example, each of these mods replaces an object known as "MapGenCaves," but because of this limitation, it isn't possible for both to just run at the same time. I could try to work around this by storing a reference to the original generator, running my own generator, and then calling whatever was previously registered, but I worry that this solution would get sloppy fairly quickly. That being said, I will try it. Like you were saying, there really is just no good way for them to interact, but there may at least be a pretty hacky way to get them to run simultaneously. I'll try this tomorrow and do some testing to see what kind of impact it has. If I can get things working, I'll consider adding it in the next version. 

Thanks for the suggestion!

**Comment by PersonTheCat** [comment]
Okay, I got this working. Let me just take a look at a few other things before I can do another release.
